name: jukebox
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - absl-py=0.12.0=pyhd8ed1ab_0
  - aiohttp=3.7.4=py37h5e8e339_0
  - async-timeout=3.0.1=py_1000
  - attrs=20.3.0=pyhd3deb0d_0
  - av=7.0.1=py37h82f89c2_2
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py37h5e8e339_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=4.2.1=pyhd8ed1ab_0
  - certifi=2020.12.5=py37h89c1867_1
  - chardet=4.0.0=py37h89c1867_1
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.4.7=py37h5d9358c_0
  - cudatoolkit=10.0.130=0
  - ffmpeg=4.2.3=h167e202_0
  - freetype=2.10.4=h5ab3b9f_0
  - gettext=0.19.8.1=hf34092f_1004
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - google-api-core=1.26.2=pyhd8ed1ab_0
  - google-api-python-client=2.0.2=pyhd8ed1ab_0
  - google-auth=1.28.0=pyh44b312d_0
  - google-auth-httplib2=0.0.4=pyh9f0ad1d_0
  - google-auth-oauthlib=0.4.1=py_2
  - googleapis-common-protos=1.53.0=py37h89c1867_0
  - grpcio=1.37.0=py37hb27c1af_0
  - httplib2=0.19.1=pyhd8ed1ab_0
  - icu=68.1=h2531618_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.10.1=py37h89c1867_0
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7f98852_1001
  - lcms2=2.11=h396b838_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hf484d3e_1007
  - libflac=1.3.3=h9c3ff4c_1
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=9.3.0=h2828fa1_18
  - libiconv=1.16=h516909a_0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.15.6=h780b84a_0
  - libsndfile=1.0.31=h9c3ff4c_0
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.1.0=h2733197_1
  - libuv=1.41.0=h7f98852_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - lz4-c=1.9.3=h2531618_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.3.0=py37h54f3939_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - mpi=1.0=mpich
  - mpi4py=3.0.3=py37hf046da1_1
  - mpich=3.3.2=hc856adb_0
  - multidict=5.1.0=py37h5e8e339_1
  - ncurses=6.2=he6710b0_1
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=py37hff7bd54_0
  - nodejs=15.11.0=h92b4a50_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=py37_0
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.1.3=py37he6710b0_0
  - pillow=8.1.1=py37he98fc37_0
  - pip=21.0.1=py37h06a4308_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyjwt=2.0.1=pyhd8ed1ab_1
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py37h89c1867_3
  - python=3.7.5=h0371630_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0
  - pytz=2021.1=pyhd8ed1ab_0
  - readline=7.0=h7b6447c_5
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - setuptools=52.0.0=py37h06a4308_0
  - simplejson=3.17.2=py37h5e8e339_2
  - six=1.15.0=py37h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.5.0=py37_cu100
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - uritemplate=3.0.1=py_0
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - x264=1!152.20180806=h14c3975_0
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.3=py37h5e8e339_1
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - anyio==2.2.0
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - audioread==2.1.9
    - babel==2.9.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cffi==1.14.5
    - decorator==4.4.2
    - defusedxml==0.7.1
    - entrypoints==0.3
    - fire==0.1.3
    - ipykernel==5.5.0
    - ipython==7.21.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==2.11.3
    - joblib==1.0.1
    - json5==0.9.5
    - jsonschema==3.2.0
    - jupyter-client==6.1.11
    - jupyter-core==4.7.1
    - jupyter-packaging==0.7.12
    - jupyter-server==1.4.1
    - jupyterlab==3.0.9
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.3.0
    - librosa==0.7.2
    - llvmlite==0.31.0
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbclassic==0.2.6
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nest-asyncio==1.5.1
    - notebook==6.2.0
    - numba==0.48.0
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.16
    - protobuf==3.15.5
    - ptyprocess==0.7.0
    - pygments==2.8.1
    - pyrsistent==0.17.3
    - pyzmq==22.0.3
    - resampy==0.2.2
    - scikit-learn==0.24.1
    - scipy==1.6.1
    - send2trash==1.5.0
    - sniffio==1.2.0
    - soundfile==0.10.3.post1
    - tensorboardx==1.8
    - terminado==0.9.2
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tornado==6.1
    - tqdm==4.45.0
    - traitlets==5.0.5
    - unidecode==1.1.1
    - urllib3==1.26.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
prefix: /opt/miniconda3/envs/jukebox
